# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('basic-apps', ['basic-sim'])
    module.source = [
        'model/flow-send-application.cc',
        'model/flow-sink.cc',
        'model/schedule-reader.cc',
        'helper/flow-send-helper.cc',
        'helper/flow-sink-helper.cc',
        'model/flow-scheduler.cc',
        'model/pingmesh-scheduler.cc',
        'model/udp-rtt-client.cc',
        'model/udp-rtt-server.cc',
        'helper/udp-rtt-helper.cc',
        'model/horovod-worker.cc',
        'model/horovod-scheduler.cc',
        'helper/horovod-worker-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('basic-apps')
    module_test.source = [
        'test/basic-apps-test-suite.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'basic-apps'
    headers.source = [
        'model/flow-send-application.h',
        'model/flow-sink.h',
        'model/schedule-reader.h',
        'helper/flow-send-helper.h',
        'helper/flow-sink-helper.h',
        'model/flow-scheduler.h',
        'model/pingmesh-scheduler.h',
        'model/udp-rtt-client.h',
        'model/udp-rtt-server.h',
        'helper/udp-rtt-helper.h',
        'model/horovod-worker.h',
        'model/horovod-scheduler.h',
        'helper/horovod-worker-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

