# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('basic-sim', ['core'])
    module.source = [
        'model/basic-sim.cc',
        'model/flow-send-application.cc',
        'model/schedule-reader.cc',
        'model/simon-util.cc',
        'model/topology.cc',
        'helper/flow-send-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('basic-sim')
    module_test.source = [
        'test/basic-sim-test-suite.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'basic-sim'
    headers.source = [
        'model/basic-sim.h',
        'model/flow-send-application.h',
        'model/schedule-reader.h',
        'model/simon-util.h',
        'model/topology.h',
        'helper/flow-send-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

