# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('basic-sim', ['core', 'internet', 'applications', 'point-to-point', 'traffic-control'])
    module.source = [
        'model/basic-simulation.cc',
        'model/flow-send-application.cc',
        'model/flow-sink.cc',
        'model/schedule-reader.cc',
        'model/simon-util.cc',
        'model/topology.cc',
        'helper/flow-send-helper.cc',
        'helper/flow-sink-helper.cc',
        'model/ipv4-arbitrary-routing.cc',
        'helper/ipv4-arbitrary-routing-helper.cc',
        'model/routing-arbiter.cc',
        'model/routing-arbiter-ecmp.cc',
        'model/flow-scheduler.cc',
        'model/pingmesh-scheduler.cc',
        ]

    module_test = bld.create_ns3_module_test_library('basic-sim')
    module_test.source = [
        'test/basic-sim-test-suite.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'basic-sim'
    headers.source = [
        'model/basic-simulation.h',
        'model/flow-send-application.h',
        'model/flow-sink.h',
        'model/schedule-reader.h',
        'model/simon-util.h',
        'model/topology.h',
        'helper/flow-send-helper.h',
        'helper/flow-sink-helper.h',
        'model/ipv4-arbitrary-routing.h',
        'helper/ipv4-arbitrary-routing-helper.h',
        'model/routing-arbiter.h',
        'model/routing-arbiter-ecmp.h',
        'model/flow-scheduler.h',
        'model/pingmesh-scheduler.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

